/**
 * The registry, the census, and the committed generated reference.
 *
 * The staleness assertions run here rather than only behind `cli-reference --check`, because a
 * check nobody remembers to run is not a check. They read the COMMITTED files — they cannot
 * regenerate, because doing so means importing the tools, and a module containing `import.meta`
 * cannot be loaded by jest. So they catch a tool being added, removed or renamed without a
 * regenerate; full drift (a changed flag or summary) is what `--check` is for.
 */
import { describe, it, expect } from "@jest/globals";
import fs from "node:fs";
import path from "node:path";
import { loadTiers, TIERS, type TierManifest } from "../tiers";
import { census, type CensusFs } from "../census";
import { flattenCommands } from "../tool-schema";

const REPO = process.cwd();
const read = (p: string) => fs.readFileSync(path.join(REPO, p), "utf8");

describe("loadTiers", () => {
  it("indexes every declared path exactly once", () => {
    const tiers = loadTiers();
    expect(tiers.all().length).toBeGreaterThan(0);
    expect(new Set(tiers.all()).size).toBe(tiers.all().length);
    expect(tiers.tierOf.get("scripts/ops/liveone.ts")).toBe("a");
    // The dashboard domain is a composable module, not a CLI: tier C, and not documented on its
    // own — the reference documents it through `liveone`.
    expect(tiers.tierOf.get("scripts/ops/dashboard/cli.ts")).toBe("c");
  });

  it("REFUSES a path listed in two tiers", () => {
    // Last-writer-wins over a,b,c,lib runs strict→loose, so a duplicate would silently be held to
    // the WEAKER standard. One nanti file sat in both tiers from day one.
    const bad: TierManifest = { a: ["x.ts"], b: ["x.ts"], c: [], lib: [] };
    expect(() => loadTiers(bad)).toThrow(/listed in both tier a and tier b/);
  });
});

describe("census", () => {
  const fakeFs = (files: Record<string, string>): CensusFs => ({
    exists: (p) => p in files,
    read: (p) => files[p] ?? "",
    list: () => Object.keys(files),
  });

  it("reports a manifest entry with no file", () => {
    const f = census(fakeFs({}), { a: ["gone.ts"], b: [], c: [], lib: [] });
    expect(f).toEqual([
      expect.objectContaining({ code: "MISSING", file: "gone.ts" }),
    ]);
  });

  it("reports a tier-A tool that is not on the harness", () => {
    const f = census(
      fakeFs({ "t.ts": "process.argv.slice(2)" }),
      { a: ["t.ts"], b: [], c: [], lib: [] },
      [],
    );
    expect(f[0].code).toBe("NOT_CONVERTED");
  });

  it("reports a converted tool that would run when imported", () => {
    const f = census(
      fakeFs({ "t.ts": "export const cmd = defineCommand({})" }),
      { a: ["t.ts"], b: [], c: [], lib: [] },
      [],
    );
    expect(f[0].code).toBe("NO_ENTRYPOINT_GUARD");
  });

  it("reports a CLI-shaped file the manifest omits — unlisted is never an exemption", () => {
    const f = census(
      fakeFs({ "scripts/ops/rogue.ts": "const a = process.argv[2]" }),
      { a: [], b: [], c: [], lib: [] },
      ["scripts/ops"],
    );
    expect(f).toEqual([
      expect.objectContaining({
        code: "UNTIERED",
        file: "scripts/ops/rogue.ts",
      }),
    ]);
  });

  it("ignores a listed non-CLI and an unlisted non-CLI", () => {
    expect(
      census(
        fakeFs({
          "scripts/ops/helper.ts": "export const x = 1",
          "lib.ts": "export const y = 2",
        }),
        { a: [], b: [], c: ["scripts/ops/helper.ts"], lib: [] },
        ["scripts/ops"],
      ),
    ).toEqual([]);
  });

  it("finds nothing in tier A for the real repo", () => {
    // The gate: tier A is the agent-facing set, and it must stay conformant.
    const tiers = loadTiers();
    const tierA = census().filter((f) => tiers.tierOf.get(f.file) === "a");
    expect(tierA).toEqual([]);
  });
});

describe("the committed reference", () => {
  const catalogue = JSON.parse(read("docs/cli-tools.json")) as {
    count: number;
    tools: {
      name: string;
      file: string;
      writes: boolean;
      input_schema: unknown;
    }[];
  };

  it("carries a DO-NOT-EDIT banner a rendered-page reader can see", () => {
    for (const f of ["docs/cli-reference.md", "scripts/ops/CLI_README.md"]) {
      const body = read(f);
      expect(body.startsWith("<!-- AUTOGENERATED")).toBe(true);
      expect(body.slice(0, 400)).toContain("Generated — do not edit.");
    }
    expect(read("docs/cli-tools.json").slice(0, 200)).toContain("DO NOT EDIT");
  });

  it("holds one entry per leaf command, unique and in code-unit order", () => {
    const names = catalogue.tools.map((t) => t.name);
    expect(catalogue.count).toBe(catalogue.tools.length);
    expect(new Set(names).size).toBe(names.length);
    // Plain sort, not localeCompare: a locale-dependent order would make the committed file
    // machine-dependent.
    expect(names).toEqual([...names].sort());
  });

  it("documents every tier-A tool, and nothing that is not tier A or B", () => {
    const tiers = loadTiers();
    const documented = new Set(catalogue.tools.map((t) => t.file));
    for (const file of documented)
      expect(["a", "b"]).toContain(tiers.tierOf.get(file));
    // Every tier-A tool appears — this is what fails when a tool is added without regenerating.
    for (const file of tiers.paths("a"))
      expect(documented.has(file)).toBe(true);
  });

  it("names the dashboard verbs under the liveone root", () => {
    // The whole point of the one-CLI shape: a leaf is addressed as `liveone dashboard <verb>`, and
    // its MCP name carries the same path.
    const names = catalogue.tools.map((t) => t.name);
    expect(names).toContain("liveone__dashboard__show");
    expect(names).not.toContain("dashboard__show");
  });

  it("agrees with the dashboard spec's own leaf count", () => {
    // Ties the catalogue to a spec that CAN be imported here (no import.meta in lib/), so adding
    // or removing a subcommand without regenerating fails.
    const dashboardEntries = catalogue.tools.filter((t) =>
      t.name.startsWith("liveone__dashboard__"),
    );
    expect(dashboardEntries.length).toBeGreaterThan(0);
    expect(
      dashboardEntries.every((t) => typeof t.input_schema === "object"),
    ).toBe(true);
  });

  it("indexes every catalogued command in docs/cli-reference.md", () => {
    const index = read("docs/cli-reference.md");
    for (const t of catalogue.tools) {
      const display = t.name.replace(/__/g, " ");
      expect(index).toContain(display);
    }
  });

  it("marks writing commands as such", () => {
    const byName = new Map(catalogue.tools.map((t) => [t.name, t]));
    expect(byName.get("liveone__dashboard__show")!.writes).toBe(false);
    expect(byName.get("liveone__dashboard__remove-node")!.writes).toBe(true);
  });
});

describe("flattenCommands over the real dashboard spec", () => {
  it("is importable from lib without running anything", () => {
    // A sanity check that the kit's own modules stay import-safe: tool files are not, by design.
    expect(typeof flattenCommands).toBe("function");
    expect(Object.keys(TIERS).sort()).toEqual(["a", "b", "c", "lib"]);
  });
});
