#!/usr/bin/env tsx
/**
 * cli-reference — generate the committed CLI documentation from the tools' own `defineCommand()`
 * blocks.
 *
 * Three outputs, all committed and NEVER hand-edited:
 *
 *   <dir>/CLI_README.md    the full `--help` for every tool in that directory — answers "what is in
 *                          this directory" for someone standing in it
 *   docs/cli-reference.md  an INDEX ONLY. It never inlines help text: that is hundreds of kilobytes
 *                          of prose, and grepping it is how you end up constructing an invocation
 *                          that no longer exists
 *   docs/cli-tools.json    the machine catalogue — one MCP-shaped tool definition per leaf command
 *
 * DISCOVERY IS THE REGISTRY, NOT A GLOB (`lib/cli/tiers.ts`), and a file is STATICALLY VERIFIED to
 * be a converted tool before it is imported. That guard is not theoretical: nanti's equivalent
 * generator, on its first run, imported unconverted tools that called `main()` at module scope —
 * which started a real inbox scan and reached its Slack notifier.
 *
 * Staleness is enforced by the TEST SUITE against the committed files, not only by `--check` here,
 * so a stale reference fails `npm test` rather than waiting for someone to remember the flag.
 */
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import {
  defineCommand,
  renderHelp,
  run,
  reachableExitCodes,
  EXIT,
  failWith,
  type CommandSpec,
  type Ctx,
} from "@/lib/cli/cli";
import {
  flattenCommands,
  walkCommandTree,
  inputSchemaFor,
  signatureFor,
  descriptionFor,
  toolNameFor,
} from "@/lib/cli/tool-schema";
import { loadTiers, type Tier } from "@/lib/cli/tiers";

const REPO = process.cwd();

export const BANNER =
  "<!-- AUTOGENERATED by scripts/ops/cli-reference.ts — DO NOT EDIT.\n" +
  "     Edit the tool's own defineCommand() block, then run:\n" +
  "       npm run cli:reference -- --apply -->";

/** Also stated in prose: a banner only a source-reader sees is no banner to whoever reads the page. */
const DO_NOT_EDIT = "**Generated — do not edit.**";

/** The three markers a file must carry before it is safe to import. */
const MARKERS = ["export const cmd", "defineCommand(", "import.meta.url"];

interface Loaded {
  file: string;
  tier: Tier;
  spec: CommandSpec;
}

interface Skipped {
  file: string;
  tier: Tier;
  reason: string;
}

async function loadTools(): Promise<{ loaded: Loaded[]; skipped: Skipped[] }> {
  const tiers = loadTiers();
  const loaded: Loaded[] = [];
  const skipped: Skipped[] = [];
  for (const tier of ["a", "b"] as const) {
    for (const file of tiers.paths(tier)) {
      const abs = path.join(REPO, file);
      if (!fs.existsSync(abs)) {
        skipped.push({
          file,
          tier,
          reason: "listed in the manifest but missing on disk",
        });
        continue;
      }
      const src = fs.readFileSync(abs, "utf8");
      const missing = MARKERS.filter((m) => !src.includes(m));
      if (missing.length) {
        // NOT an error: tier B holds tools that predate the harness. It is a reported gap.
        skipped.push({
          file,
          tier,
          reason: `not on the shared harness (no ${missing.join(", ")})`,
        });
        continue;
      }
      const mod = (await import(pathToFileURL(abs).href)) as {
        cmd?: CommandSpec;
      };
      if (!mod.cmd) {
        skipped.push({ file, tier, reason: "does not export `cmd`" });
        continue;
      }
      loaded.push({ file, tier, spec: mod.cmd });
    }
  }
  return { loaded, skipped };
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

const COMMON_PREAMBLE = [
  "Every command takes `--help` and `--format human|json` (human at a terminal, json when piped);",
  "the data-download commands also accept `--format csv` — their help says so.",
  "Data goes to stdout; all diagnostics go to stderr. Mutating commands are **dry by default** —",
  "`--apply` writes, and off a terminal `--apply` additionally requires `--yes`.",
  "",
  "| Exit | Meaning |",
  "| ---- | ------- |",
  "| 0 | success |",
  "| 1 | completed, with findings or no results |",
  "| 2 | usage error — nothing was attempted |",
  "| 3 | authentication failure |",
  "| 5 | upstream failure |",
  "| 130 | interrupted |",
].join("\n");

function renderDirReadme(dir: string, tools: Loaded[]): string {
  const out = [BANNER, "", `# CLIs in \`${dir}\``, "", DO_NOT_EDIT, ""];
  out.push(
    `${tools.length} tool(s). Indexed from [docs/cli-reference.md](${path.relative(dir, "docs/cli-reference.md")}).`,
    "",
    COMMON_PREAMBLE,
    "",
    "## Contents",
    "",
  );
  for (const t of tools)
    for (const node of walkCommandTree(t.spec))
      out.push(
        `${"  ".repeat(node.path.length - 1)}- [${node.path.join(" ")}](#${node.path.join("-")})` +
          (node.spec.mutates ? "  _(writes)_" : ""),
      );
  out.push("");
  for (const t of tools) {
    // EVERY node, not just leaves: a reader needs the intermediate domain's own help (including
    // its safety text), and a leaf's usage line needs its full ancestor chain or it renders as
    // `liveone show` with the domain silently missing.
    for (const node of walkCommandTree(t.spec)) {
      const depth = node.path.length;
      out.push(
        `${"#".repeat(Math.min(depth + 1, 6))} ${node.path.join(" ")}`,
        "",
        node.spec.summary,
        "",
      );
      if (depth === 1)
        out.push(`\`npm run ${t.spec.name}\` — \`${t.file}\``, "");
      out.push("```", renderHelp(node.spec, node.ancestors), "```", "");
    }
  }
  return out.join("\n").replace(/\n*$/, "\n");
}

function renderIndex(byDir: Map<string, Loaded[]>): string {
  const out = [
    BANNER,
    "",
    "# CLI reference",
    "",
    DO_NOT_EDIT,
    "",
    "An **index only** — the full `--help` for each tool lives beside it in that directory's",
    "`CLI_README.md`. This answers *what tools exist*; it deliberately does not answer *which",
    "command does X*, because a wall of prose is the wrong place to look that up. For that, read",
    "the machine catalogue at [cli-tools.json](cli-tools.json).",
    "",
    COMMON_PREAMBLE,
    "",
  ];
  for (const [dir, tools] of [...byDir].sort()) {
    out.push(`## \`${dir}\``, "");
    for (const t of tools) {
      const readme = path.relative("docs", path.join(dir, "CLI_README.md"));
      for (const node of walkCommandTree(t.spec))
        out.push(
          `${"  ".repeat(node.path.length - 1)}- [${node.path.join(" ")}](${readme}#${node.path.join("-")}) — ${node.spec.summary}` +
            (node.spec.mutates ? "  _(writes)_" : ""),
        );
    }
    out.push("");
  }
  return out.join("\n").replace(/\n*$/, "\n");
}

function renderCatalogue(loaded: Loaded[]): string {
  const tools = loaded
    .flatMap((t) =>
      flattenCommands(t.spec).map((leaf) => ({
        name: toolNameFor(leaf.path),
        summary: leaf.spec.summary,
        when: leaf.spec.when ?? "",
        parentWhen: leaf.parentWhen ?? "",
        description: descriptionFor(leaf, { file: t.file }),
        input_schema: inputSchemaFor(leaf.spec),
        signature: signatureFor(leaf),
        invocation: `npm run ${leaf.path[0]} --${leaf.path.length > 1 ? ` ${leaf.path.slice(1).join(" ")}` : ""}`,
        file: t.file,
        writes: !!leaf.spec.mutates,
        exitCodes: reachableExitCodes(leaf.spec),
      })),
    )
    // Plain code-unit order, NOT localeCompare: a locale-dependent sort would make the committed
    // file machine-dependent, and it folds `-` and `_`.
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

  return (
    JSON.stringify(
      {
        $comment:
          "AUTOGENERATED by scripts/ops/cli-reference.ts — DO NOT EDIT. Edit the tool's defineCommand() block and re-run.",
        note:
          "One entry per invocable leaf command. `--quiet`, `--color`, `--help` and the `--json` alias are " +
          "omitted from every input_schema as noise; output is json when stdout is not a terminal; and a " +
          "command with `writes: true` changes nothing until --apply (plus --yes off a terminal).",
        count: tools.length,
        tools,
      },
      null,
      2,
    ) + "\n"
  );
}

// ---------------------------------------------------------------------------
// Targets
// ---------------------------------------------------------------------------

export interface Target {
  path: string;
  body: string;
}

/** Every file this generator owns, with the body it should currently have. */
export async function computeTargets(): Promise<{
  targets: Target[];
  skipped: Skipped[];
  loaded: Loaded[];
}> {
  const { loaded, skipped } = await loadTools();
  const byDir = new Map<string, Loaded[]>();
  for (const t of loaded) {
    const dir = path.dirname(t.file);
    (byDir.get(dir) ?? byDir.set(dir, []).get(dir)!).push(t);
  }
  const targets: Target[] = [];
  for (const [dir, tools] of byDir)
    targets.push({
      path: path.join(dir, "CLI_README.md"),
      body: renderDirReadme(dir, tools),
    });
  targets.push({ path: "docs/cli-reference.md", body: renderIndex(byDir) });
  targets.push({ path: "docs/cli-tools.json", body: renderCatalogue(loaded) });
  return { targets, skipped, loaded };
}

function isStale(t: Target): boolean {
  const abs = path.join(REPO, t.path);
  return !fs.existsSync(abs) || fs.readFileSync(abs, "utf8") !== t.body;
}

/**
 * Orphans: a `CLI_README.md` in a directory that no longer holds a documented CLI. REPORTED, never
 * deleted — this tool owns the files it generates, not every file that looks like one.
 */
function findOrphans(targets: Target[]): string[] {
  const owned = new Set(targets.map((t) => t.path));
  const found: string[] = [];
  const walk = (dir: string, depth: number): void => {
    if (depth > 5) return;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(path.join(REPO, dir), { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (e.name === "node_modules" || e.name.startsWith(".")) continue;
      const rel = path.join(dir, e.name);
      if (e.isDirectory()) walk(rel, depth + 1);
      else if (e.name === "CLI_README.md" && !owned.has(rel)) found.push(rel);
    }
  };
  walk("scripts", 0);
  return found;
}

// ---------------------------------------------------------------------------
// Command
// ---------------------------------------------------------------------------

export const cmd = defineCommand({
  name: "cli-reference",
  summary:
    "Regenerate the committed CLI documentation from the tools' own declarations.",
  when:
    "Run this after changing any tool's defineCommand() block — its summary, flags, examples or\n" +
    "subcommands. The generated files are committed, and `npm test` fails when they are stale, so\n" +
    "this is the fix for that failure. Never hand-edit the generated files.",
  description:
    "Writes <dir>/CLI_README.md (the full --help), docs/cli-reference.md (an index only) and\n" +
    "docs/cli-tools.json (the machine catalogue). Discovery is the registry in lib/cli/tiers.ts,\n" +
    "not a glob, and a file is statically checked for `export const cmd` / `defineCommand(` /\n" +
    "`import.meta.url` before it is imported — importing an unconverted tool would RUN it.",
  mutates: true,
  flags: {
    check: {
      type: "boolean",
      help: "Write nothing; exit 1 if any generated file is stale or a tool failed to load",
    },
  },
  exitCodes: {
    1: "generated files are stale (--check), or a listed tool could not be loaded",
  },
  examples: [
    "npm run cli:reference",
    "npm run cli:reference -- --apply",
    "npm run cli:reference -- --check",
  ],
});

async function main(ctx: Ctx): Promise<number> {
  const { targets, skipped, loaded } = await computeTargets();
  const stale = targets.filter(isStale);
  const orphans = findOrphans(targets);
  const check = ctx.flags.check === true;

  if (!check && !ctx.dryRun)
    for (const t of stale) fs.writeFileSync(path.join(REPO, t.path), t.body);

  for (const s of skipped)
    ctx.warn(`  SKIP ${s.file} (tier ${s.tier}): ${s.reason}`);
  for (const o of orphans)
    ctx.warn(
      `  ORPHAN ${o}: no documented CLI in that directory — delete it by hand if it is dead`,
    );

  ctx.emit(
    {
      tools: loaded.length,
      commands: JSON.parse(
        targets.find((t) => t.path === "docs/cli-tools.json")!.body,
      ).count,
      // Named, not counted: "something is stale over seven files" is a scavenger hunt.
      stale: stale.map((t) => t.path),
      skipped,
      orphans,
      applied: !check && !ctx.dryRun,
    },
    (m: never) => {
      const model = m as {
        tools: number;
        commands: number;
        stale: string[];
        applied: boolean;
      };
      const out = [
        `${model.tools} tool(s), ${model.commands} command(s) documented.`,
      ];
      if (!model.stale.length) out.push("Everything is up to date.");
      else {
        out.push(
          `${model.stale.length} file(s) ${model.applied ? "written" : "would change"}:`,
          ...model.stale.slice(0, 8).map((p) => `  ${p}`),
        );
        if (model.stale.length > 8)
          out.push(`  … ${model.stale.length - 8} more`);
        if (!model.applied) out.push("Re-run with --apply to write.");
      }
      return out.join("\n");
    },
  );

  // A tool that failed to load means the catalogue is INCOMPLETE, which --check must fail on even
  // when nothing is stale — otherwise it reports "up to date" about a reference missing a tool.
  const failedLoad = skipped.filter((s) => s.tier === "a").length > 0;
  if (check && (stale.length > 0 || failedLoad)) return EXIT.FINDINGS;
  if (failedLoad && !check)
    throw failWith(
      EXIT.FINDINGS,
      "a tier-A tool could not be loaded",
      "the generated reference is missing a tool that is supposed to be in it",
      "convert the tool to the shared harness, or move it to a lower tier",
    );
  return EXIT.OK;
}

run(cmd, main, import.meta.url);
