/**
 * Timezone utilities for display timezone selection
 * Contains all 139 canonical IANA timezones grouped by region
 */

export interface TimezoneOption {
  value: string; // IANA timezone string (e.g., "Australia/Melbourne")
  label: string; // Display name (e.g., "Melbourne")
  region: string; // Region grouping
}

export interface TimezoneGroup {
  region: string;
  timezones: TimezoneOption[];
}

/**
 * All 139 canonical IANA timezones
 * Source: IANA Time Zone Database
 */
export const CANONICAL_TIMEZONES: TimezoneOption[] = [
  // Africa
  { value: "Africa/Abidjan", label: "Abidjan", region: "Africa" },
  { value: "Africa/Accra", label: "Accra", region: "Africa" },
  { value: "Africa/Algiers", label: "Algiers", region: "Africa" },
  { value: "Africa/Bissau", label: "Bissau", region: "Africa" },
  { value: "Africa/Cairo", label: "Cairo", region: "Africa" },
  { value: "Africa/Casablanca", label: "Casablanca", region: "Africa" },
  { value: "Africa/Ceuta", label: "Ceuta", region: "Africa" },
  { value: "Africa/El_Aaiun", label: "El Aaiun", region: "Africa" },
  { value: "Africa/Johannesburg", label: "Johannesburg", region: "Africa" },
  { value: "Africa/Juba", label: "Juba", region: "Africa" },
  { value: "Africa/Khartoum", label: "Khartoum", region: "Africa" },
  { value: "Africa/Lagos", label: "Lagos", region: "Africa" },
  { value: "Africa/Maputo", label: "Maputo", region: "Africa" },
  { value: "Africa/Monrovia", label: "Monrovia", region: "Africa" },
  { value: "Africa/Nairobi", label: "Nairobi", region: "Africa" },
  { value: "Africa/Ndjamena", label: "Ndjamena", region: "Africa" },
  { value: "Africa/Sao_Tome", label: "Sao Tome", region: "Africa" },
  { value: "Africa/Tripoli", label: "Tripoli", region: "Africa" },
  { value: "Africa/Tunis", label: "Tunis", region: "Africa" },
  { value: "Africa/Windhoek", label: "Windhoek", region: "Africa" },

  // Americas
  { value: "America/Adak", label: "Adak", region: "Americas" },
  { value: "America/Anchorage", label: "Anchorage", region: "Americas" },
  { value: "America/Araguaina", label: "Araguaina", region: "Americas" },
  {
    value: "America/Argentina/Buenos_Aires",
    label: "Buenos Aires",
    region: "Americas",
  },
  {
    value: "America/Argentina/Catamarca",
    label: "Catamarca",
    region: "Americas",
  },
  { value: "America/Argentina/Cordoba", label: "Cordoba", region: "Americas" },
  { value: "America/Argentina/Jujuy", label: "Jujuy", region: "Americas" },
  {
    value: "America/Argentina/La_Rioja",
    label: "La Rioja",
    region: "Americas",
  },
  { value: "America/Argentina/Mendoza", label: "Mendoza", region: "Americas" },
  {
    value: "America/Argentina/Rio_Gallegos",
    label: "Rio Gallegos",
    region: "Americas",
  },
  { value: "America/Argentina/Salta", label: "Salta", region: "Americas" },
  {
    value: "America/Argentina/San_Juan",
    label: "San Juan",
    region: "Americas",
  },
  {
    value: "America/Argentina/San_Luis",
    label: "San Luis",
    region: "Americas",
  },
  { value: "America/Argentina/Tucuman", label: "Tucuman", region: "Americas" },
  { value: "America/Argentina/Ushuaia", label: "Ushuaia", region: "Americas" },
  { value: "America/Asuncion", label: "Asuncion", region: "Americas" },
  { value: "America/Bahia", label: "Bahia", region: "Americas" },
  {
    value: "America/Bahia_Banderas",
    label: "Bahia Banderas",
    region: "Americas",
  },
  { value: "America/Barbados", label: "Barbados", region: "Americas" },
  { value: "America/Belem", label: "Belem", region: "Americas" },
  { value: "America/Belize", label: "Belize", region: "Americas" },
  { value: "America/Boa_Vista", label: "Boa Vista", region: "Americas" },
  { value: "America/Bogota", label: "Bogota", region: "Americas" },
  { value: "America/Boise", label: "Boise", region: "Americas" },
  {
    value: "America/Cambridge_Bay",
    label: "Cambridge Bay",
    region: "Americas",
  },
  { value: "America/Campo_Grande", label: "Campo Grande", region: "Americas" },
  { value: "America/Cancun", label: "Cancun", region: "Americas" },
  { value: "America/Caracas", label: "Caracas", region: "Americas" },
  { value: "America/Cayenne", label: "Cayenne", region: "Americas" },
  { value: "America/Chicago", label: "Chicago", region: "Americas" },
  { value: "America/Chihuahua", label: "Chihuahua", region: "Americas" },
  {
    value: "America/Ciudad_Juarez",
    label: "Ciudad Juarez",
    region: "Americas",
  },
  { value: "America/Costa_Rica", label: "Costa Rica", region: "Americas" },
  { value: "America/Cuiaba", label: "Cuiaba", region: "Americas" },
  { value: "America/Danmarkshavn", label: "Danmarkshavn", region: "Americas" },
  { value: "America/Dawson", label: "Dawson", region: "Americas" },
  { value: "America/Dawson_Creek", label: "Dawson Creek", region: "Americas" },
  { value: "America/Denver", label: "Denver", region: "Americas" },
  { value: "America/Detroit", label: "Detroit", region: "Americas" },
  { value: "America/Edmonton", label: "Edmonton", region: "Americas" },
  { value: "America/Eirunepe", label: "Eirunepe", region: "Americas" },
  { value: "America/El_Salvador", label: "El Salvador", region: "Americas" },
  { value: "America/Fort_Nelson", label: "Fort Nelson", region: "Americas" },
  { value: "America/Fortaleza", label: "Fortaleza", region: "Americas" },
  { value: "America/Glace_Bay", label: "Glace Bay", region: "Americas" },
  { value: "America/Goose_Bay", label: "Goose Bay", region: "Americas" },
  { value: "America/Grand_Turk", label: "Grand Turk", region: "Americas" },
  { value: "America/Guatemala", label: "Guatemala", region: "Americas" },
  { value: "America/Guayaquil", label: "Guayaquil", region: "Americas" },
  { value: "America/Guyana", label: "Guyana", region: "Americas" },
  { value: "America/Halifax", label: "Halifax", region: "Americas" },
  { value: "America/Havana", label: "Havana", region: "Americas" },
  { value: "America/Hermosillo", label: "Hermosillo", region: "Americas" },
  {
    value: "America/Indiana/Indianapolis",
    label: "Indianapolis",
    region: "Americas",
  },
  { value: "America/Indiana/Knox", label: "Knox, Indiana", region: "Americas" },
  {
    value: "America/Indiana/Marengo",
    label: "Marengo, Indiana",
    region: "Americas",
  },
  {
    value: "America/Indiana/Petersburg",
    label: "Petersburg, Indiana",
    region: "Americas",
  },
  {
    value: "America/Indiana/Tell_City",
    label: "Tell City, Indiana",
    region: "Americas",
  },
  {
    value: "America/Indiana/Vevay",
    label: "Vevay, Indiana",
    region: "Americas",
  },
  {
    value: "America/Indiana/Vincennes",
    label: "Vincennes, Indiana",
    region: "Americas",
  },
  {
    value: "America/Indiana/Winamac",
    label: "Winamac, Indiana",
    region: "Americas",
  },
  { value: "America/Inuvik", label: "Inuvik", region: "Americas" },
  { value: "America/Iqaluit", label: "Iqaluit", region: "Americas" },
  { value: "America/Jamaica", label: "Jamaica", region: "Americas" },
  { value: "America/Juneau", label: "Juneau", region: "Americas" },
  {
    value: "America/Kentucky/Louisville",
    label: "Louisville, Kentucky",
    region: "Americas",
  },
  {
    value: "America/Kentucky/Monticello",
    label: "Monticello, Kentucky",
    region: "Americas",
  },
  { value: "America/La_Paz", label: "La Paz", region: "Americas" },
  { value: "America/Lima", label: "Lima", region: "Americas" },
  { value: "America/Los_Angeles", label: "Los Angeles", region: "Americas" },
  { value: "America/Maceio", label: "Maceio", region: "Americas" },
  { value: "America/Managua", label: "Managua", region: "Americas" },
  { value: "America/Manaus", label: "Manaus", region: "Americas" },
  { value: "America/Martinique", label: "Martinique", region: "Americas" },
  { value: "America/Matamoros", label: "Matamoros", region: "Americas" },
  { value: "America/Mazatlan", label: "Mazatlan", region: "Americas" },
  { value: "America/Menominee", label: "Menominee", region: "Americas" },
  { value: "America/Merida", label: "Merida", region: "Americas" },
  { value: "America/Metlakatla", label: "Metlakatla", region: "Americas" },
  { value: "America/Mexico_City", label: "Mexico City", region: "Americas" },
  { value: "America/Miquelon", label: "Miquelon", region: "Americas" },
  { value: "America/Moncton", label: "Moncton", region: "Americas" },
  { value: "America/Monterrey", label: "Monterrey", region: "Americas" },
  { value: "America/Montevideo", label: "Montevideo", region: "Americas" },
  { value: "America/New_York", label: "New York", region: "Americas" },
  { value: "America/Nome", label: "Nome", region: "Americas" },
  { value: "America/Noronha", label: "Noronha", region: "Americas" },
  {
    value: "America/North_Dakota/Beulah",
    label: "Beulah, North Dakota",
    region: "Americas",
  },
  {
    value: "America/North_Dakota/Center",
    label: "Center, North Dakota",
    region: "Americas",
  },
  {
    value: "America/North_Dakota/New_Salem",
    label: "New Salem, North Dakota",
    region: "Americas",
  },
  { value: "America/Nuuk", label: "Nuuk", region: "Americas" },
  { value: "America/Ojinaga", label: "Ojinaga", region: "Americas" },
  { value: "America/Panama", label: "Panama", region: "Americas" },
  { value: "America/Paramaribo", label: "Paramaribo", region: "Americas" },
  { value: "America/Phoenix", label: "Phoenix", region: "Americas" },
  {
    value: "America/Port-au-Prince",
    label: "Port-au-Prince",
    region: "Americas",
  },
  { value: "America/Porto_Velho", label: "Porto Velho", region: "Americas" },
  { value: "America/Puerto_Rico", label: "Puerto Rico", region: "Americas" },
  { value: "America/Punta_Arenas", label: "Punta Arenas", region: "Americas" },
  { value: "America/Rankin_Inlet", label: "Rankin Inlet", region: "Americas" },
  { value: "America/Recife", label: "Recife", region: "Americas" },
  { value: "America/Regina", label: "Regina", region: "Americas" },
  { value: "America/Resolute", label: "Resolute", region: "Americas" },
  { value: "America/Rio_Branco", label: "Rio Branco", region: "Americas" },
  { value: "America/Santarem", label: "Santarem", region: "Americas" },
  { value: "America/Santiago", label: "Santiago", region: "Americas" },
  {
    value: "America/Santo_Domingo",
    label: "Santo Domingo",
    region: "Americas",
  },
  { value: "America/Sao_Paulo", label: "Sao Paulo", region: "Americas" },
  { value: "America/Scoresbysund", label: "Scoresbysund", region: "Americas" },
  { value: "America/Sitka", label: "Sitka", region: "Americas" },
  { value: "America/St_Johns", label: "St Johns", region: "Americas" },
  {
    value: "America/Swift_Current",
    label: "Swift Current",
    region: "Americas",
  },
  { value: "America/Tegucigalpa", label: "Tegucigalpa", region: "Americas" },
  { value: "America/Thule", label: "Thule", region: "Americas" },
  { value: "America/Tijuana", label: "Tijuana", region: "Americas" },
  { value: "America/Toronto", label: "Toronto", region: "Americas" },
  { value: "America/Vancouver", label: "Vancouver", region: "Americas" },
  { value: "America/Whitehorse", label: "Whitehorse", region: "Americas" },
  { value: "America/Winnipeg", label: "Winnipeg", region: "Americas" },
  { value: "America/Yakutat", label: "Yakutat", region: "Americas" },

  // Antarctica
  { value: "Antarctica/Casey", label: "Casey", region: "Antarctica" },
  { value: "Antarctica/Davis", label: "Davis", region: "Antarctica" },
  { value: "Antarctica/Macquarie", label: "Macquarie", region: "Antarctica" },
  { value: "Antarctica/Mawson", label: "Mawson", region: "Antarctica" },
  { value: "Antarctica/Palmer", label: "Palmer", region: "Antarctica" },
  { value: "Antarctica/Rothera", label: "Rothera", region: "Antarctica" },
  { value: "Antarctica/Troll", label: "Troll", region: "Antarctica" },

  // Asia
  { value: "Asia/Almaty", label: "Almaty", region: "Asia" },
  { value: "Asia/Amman", label: "Amman", region: "Asia" },
  { value: "Asia/Anadyr", label: "Anadyr", region: "Asia" },
  { value: "Asia/Aqtau", label: "Aqtau", region: "Asia" },
  { value: "Asia/Aqtobe", label: "Aqtobe", region: "Asia" },
  { value: "Asia/Ashgabat", label: "Ashgabat", region: "Asia" },
  { value: "Asia/Atyrau", label: "Atyrau", region: "Asia" },
  { value: "Asia/Baghdad", label: "Baghdad", region: "Asia" },
  { value: "Asia/Baku", label: "Baku", region: "Asia" },
  { value: "Asia/Bangkok", label: "Bangkok", region: "Asia" },
  { value: "Asia/Barnaul", label: "Barnaul", region: "Asia" },
  { value: "Asia/Beirut", label: "Beirut", region: "Asia" },
  { value: "Asia/Bishkek", label: "Bishkek", region: "Asia" },
  { value: "Asia/Chita", label: "Chita", region: "Asia" },
  { value: "Asia/Choibalsan", label: "Choibalsan", region: "Asia" },
  { value: "Asia/Colombo", label: "Colombo", region: "Asia" },
  { value: "Asia/Damascus", label: "Damascus", region: "Asia" },
  { value: "Asia/Dhaka", label: "Dhaka", region: "Asia" },
  { value: "Asia/Dili", label: "Dili", region: "Asia" },
  { value: "Asia/Dubai", label: "Dubai", region: "Asia" },
  { value: "Asia/Dushanbe", label: "Dushanbe", region: "Asia" },
  { value: "Asia/Famagusta", label: "Famagusta", region: "Asia" },
  { value: "Asia/Gaza", label: "Gaza", region: "Asia" },
  { value: "Asia/Hebron", label: "Hebron", region: "Asia" },
  { value: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh", region: "Asia" },
  { value: "Asia/Hong_Kong", label: "Hong Kong", region: "Asia" },
  { value: "Asia/Hovd", label: "Hovd", region: "Asia" },
  { value: "Asia/Irkutsk", label: "Irkutsk", region: "Asia" },
  { value: "Asia/Jakarta", label: "Jakarta", region: "Asia" },
  { value: "Asia/Jayapura", label: "Jayapura", region: "Asia" },
  { value: "Asia/Jerusalem", label: "Jerusalem", region: "Asia" },
  { value: "Asia/Kabul", label: "Kabul", region: "Asia" },
  { value: "Asia/Kamchatka", label: "Kamchatka", region: "Asia" },
  { value: "Asia/Karachi", label: "Karachi", region: "Asia" },
  { value: "Asia/Kathmandu", label: "Kathmandu", region: "Asia" },
  { value: "Asia/Khandyga", label: "Khandyga", region: "Asia" },
  { value: "Asia/Kolkata", label: "Kolkata", region: "Asia" },
  { value: "Asia/Krasnoyarsk", label: "Krasnoyarsk", region: "Asia" },
  { value: "Asia/Kuching", label: "Kuching", region: "Asia" },
  { value: "Asia/Macau", label: "Macau", region: "Asia" },
  { value: "Asia/Magadan", label: "Magadan", region: "Asia" },
  { value: "Asia/Makassar", label: "Makassar", region: "Asia" },
  { value: "Asia/Manila", label: "Manila", region: "Asia" },
  { value: "Asia/Nicosia", label: "Nicosia", region: "Asia" },
  { value: "Asia/Novokuznetsk", label: "Novokuznetsk", region: "Asia" },
  { value: "Asia/Novosibirsk", label: "Novosibirsk", region: "Asia" },
  { value: "Asia/Omsk", label: "Omsk", region: "Asia" },
  { value: "Asia/Oral", label: "Oral", region: "Asia" },
  { value: "Asia/Pontianak", label: "Pontianak", region: "Asia" },
  { value: "Asia/Pyongyang", label: "Pyongyang", region: "Asia" },
  { value: "Asia/Qatar", label: "Qatar", region: "Asia" },
  { value: "Asia/Qostanay", label: "Qostanay", region: "Asia" },
  { value: "Asia/Qyzylorda", label: "Qyzylorda", region: "Asia" },
  { value: "Asia/Riyadh", label: "Riyadh", region: "Asia" },
  { value: "Asia/Sakhalin", label: "Sakhalin", region: "Asia" },
  { value: "Asia/Samarkand", label: "Samarkand", region: "Asia" },
  { value: "Asia/Seoul", label: "Seoul", region: "Asia" },
  { value: "Asia/Shanghai", label: "Shanghai", region: "Asia" },
  { value: "Asia/Singapore", label: "Singapore", region: "Asia" },
  { value: "Asia/Srednekolymsk", label: "Srednekolymsk", region: "Asia" },
  { value: "Asia/Taipei", label: "Taipei", region: "Asia" },
  { value: "Asia/Tashkent", label: "Tashkent", region: "Asia" },
  { value: "Asia/Tbilisi", label: "Tbilisi", region: "Asia" },
  { value: "Asia/Tehran", label: "Tehran", region: "Asia" },
  { value: "Asia/Thimphu", label: "Thimphu", region: "Asia" },
  { value: "Asia/Tokyo", label: "Tokyo", region: "Asia" },
  { value: "Asia/Tomsk", label: "Tomsk", region: "Asia" },
  { value: "Asia/Ulaanbaatar", label: "Ulaanbaatar", region: "Asia" },
  { value: "Asia/Urumqi", label: "Urumqi", region: "Asia" },
  { value: "Asia/Ust-Nera", label: "Ust-Nera", region: "Asia" },
  { value: "Asia/Vladivostok", label: "Vladivostok", region: "Asia" },
  { value: "Asia/Yakutsk", label: "Yakutsk", region: "Asia" },
  { value: "Asia/Yangon", label: "Yangon", region: "Asia" },
  { value: "Asia/Yekaterinburg", label: "Yekaterinburg", region: "Asia" },
  { value: "Asia/Yerevan", label: "Yerevan", region: "Asia" },

  // Atlantic
  { value: "Atlantic/Azores", label: "Azores", region: "Atlantic" },
  { value: "Atlantic/Bermuda", label: "Bermuda", region: "Atlantic" },
  { value: "Atlantic/Canary", label: "Canary", region: "Atlantic" },
  { value: "Atlantic/Cape_Verde", label: "Cape Verde", region: "Atlantic" },
  { value: "Atlantic/Faroe", label: "Faroe", region: "Atlantic" },
  { value: "Atlantic/Madeira", label: "Madeira", region: "Atlantic" },
  {
    value: "Atlantic/South_Georgia",
    label: "South Georgia",
    region: "Atlantic",
  },
  { value: "Atlantic/Stanley", label: "Stanley", region: "Atlantic" },

  // Australia
  { value: "Australia/Adelaide", label: "Adelaide", region: "Australia" },
  { value: "Australia/Brisbane", label: "Brisbane", region: "Australia" },
  { value: "Australia/Broken_Hill", label: "Broken Hill", region: "Australia" },
  { value: "Australia/Darwin", label: "Darwin", region: "Australia" },
  { value: "Australia/Eucla", label: "Eucla", region: "Australia" },
  { value: "Australia/Hobart", label: "Hobart", region: "Australia" },
  { value: "Australia/Lindeman", label: "Lindeman", region: "Australia" },
  { value: "Australia/Lord_Howe", label: "Lord Howe", region: "Australia" },
  { value: "Australia/Melbourne", label: "Melbourne", region: "Australia" },
  { value: "Australia/Perth", label: "Perth", region: "Australia" },
  { value: "Australia/Sydney", label: "Sydney", region: "Australia" },

  // Europe
  { value: "Europe/Andorra", label: "Andorra", region: "Europe" },
  { value: "Europe/Astrakhan", label: "Astrakhan", region: "Europe" },
  { value: "Europe/Athens", label: "Athens", region: "Europe" },
  { value: "Europe/Belgrade", label: "Belgrade", region: "Europe" },
  { value: "Europe/Berlin", label: "Berlin", region: "Europe" },
  { value: "Europe/Brussels", label: "Brussels", region: "Europe" },
  { value: "Europe/Bucharest", label: "Bucharest", region: "Europe" },
  { value: "Europe/Budapest", label: "Budapest", region: "Europe" },
  { value: "Europe/Chisinau", label: "Chisinau", region: "Europe" },
  { value: "Europe/Dublin", label: "Dublin", region: "Europe" },
  { value: "Europe/Gibraltar", label: "Gibraltar", region: "Europe" },
  { value: "Europe/Helsinki", label: "Helsinki", region: "Europe" },
  { value: "Europe/Istanbul", label: "Istanbul", region: "Europe" },
  { value: "Europe/Kaliningrad", label: "Kaliningrad", region: "Europe" },
  { value: "Europe/Kirov", label: "Kirov", region: "Europe" },
  { value: "Europe/Kyiv", label: "Kyiv", region: "Europe" },
  { value: "Europe/Lisbon", label: "Lisbon", region: "Europe" },
  { value: "Europe/London", label: "London", region: "Europe" },
  { value: "Europe/Madrid", label: "Madrid", region: "Europe" },
  { value: "Europe/Malta", label: "Malta", region: "Europe" },
  { value: "Europe/Minsk", label: "Minsk", region: "Europe" },
  { value: "Europe/Moscow", label: "Moscow", region: "Europe" },
  { value: "Europe/Paris", label: "Paris", region: "Europe" },
  { value: "Europe/Prague", label: "Prague", region: "Europe" },
  { value: "Europe/Riga", label: "Riga", region: "Europe" },
  { value: "Europe/Rome", label: "Rome", region: "Europe" },
  { value: "Europe/Samara", label: "Samara", region: "Europe" },
  { value: "Europe/Saratov", label: "Saratov", region: "Europe" },
  { value: "Europe/Simferopol", label: "Simferopol", region: "Europe" },
  { value: "Europe/Sofia", label: "Sofia", region: "Europe" },
  { value: "Europe/Tallinn", label: "Tallinn", region: "Europe" },
  { value: "Europe/Tirane", label: "Tirane", region: "Europe" },
  { value: "Europe/Ulyanovsk", label: "Ulyanovsk", region: "Europe" },
  { value: "Europe/Vienna", label: "Vienna", region: "Europe" },
  { value: "Europe/Vilnius", label: "Vilnius", region: "Europe" },
  { value: "Europe/Volgograd", label: "Volgograd", region: "Europe" },
  { value: "Europe/Warsaw", label: "Warsaw", region: "Europe" },
  { value: "Europe/Zurich", label: "Zurich", region: "Europe" },

  // Indian
  { value: "Indian/Chagos", label: "Chagos", region: "Indian" },
  { value: "Indian/Maldives", label: "Maldives", region: "Indian" },
  { value: "Indian/Mauritius", label: "Mauritius", region: "Indian" },

  // Pacific
  { value: "Pacific/Apia", label: "Apia", region: "Pacific" },
  { value: "Pacific/Auckland", label: "Auckland", region: "Pacific" },
  { value: "Pacific/Bougainville", label: "Bougainville", region: "Pacific" },
  { value: "Pacific/Chatham", label: "Chatham", region: "Pacific" },
  { value: "Pacific/Easter", label: "Easter", region: "Pacific" },
  { value: "Pacific/Efate", label: "Efate", region: "Pacific" },
  { value: "Pacific/Fakaofo", label: "Fakaofo", region: "Pacific" },
  { value: "Pacific/Fiji", label: "Fiji", region: "Pacific" },
  { value: "Pacific/Galapagos", label: "Galapagos", region: "Pacific" },
  { value: "Pacific/Gambier", label: "Gambier", region: "Pacific" },
  { value: "Pacific/Guadalcanal", label: "Guadalcanal", region: "Pacific" },
  { value: "Pacific/Guam", label: "Guam", region: "Pacific" },
  { value: "Pacific/Honolulu", label: "Honolulu", region: "Pacific" },
  { value: "Pacific/Kanton", label: "Kanton", region: "Pacific" },
  { value: "Pacific/Kiritimati", label: "Kiritimati", region: "Pacific" },
  { value: "Pacific/Kosrae", label: "Kosrae", region: "Pacific" },
  { value: "Pacific/Kwajalein", label: "Kwajalein", region: "Pacific" },
  { value: "Pacific/Marquesas", label: "Marquesas", region: "Pacific" },
  { value: "Pacific/Nauru", label: "Nauru", region: "Pacific" },
  { value: "Pacific/Niue", label: "Niue", region: "Pacific" },
  { value: "Pacific/Norfolk", label: "Norfolk", region: "Pacific" },
  { value: "Pacific/Noumea", label: "Noumea", region: "Pacific" },
  { value: "Pacific/Pago_Pago", label: "Pago Pago", region: "Pacific" },
  { value: "Pacific/Palau", label: "Palau", region: "Pacific" },
  { value: "Pacific/Pitcairn", label: "Pitcairn", region: "Pacific" },
  { value: "Pacific/Port_Moresby", label: "Port Moresby", region: "Pacific" },
  { value: "Pacific/Rarotonga", label: "Rarotonga", region: "Pacific" },
  { value: "Pacific/Tahiti", label: "Tahiti", region: "Pacific" },
  { value: "Pacific/Tarawa", label: "Tarawa", region: "Pacific" },
  { value: "Pacific/Tongatapu", label: "Tongatapu", region: "Pacific" },

  // UTC
  { value: "UTC", label: "UTC", region: "UTC" },
];

/**
 * Group timezones by region for display in dropdown
 */
export const TIMEZONE_GROUPS: TimezoneGroup[] = [
  "Australia",
  "Pacific",
  "Asia",
  "Europe",
  "Africa",
  "Americas",
  "Atlantic",
  "Indian",
  "Antarctica",
  "UTC",
].map((region) => ({
  region,
  timezones: CANONICAL_TIMEZONES.filter((tz) => tz.region === region),
}));

/**
 * Validate if a timezone string is a canonical IANA timezone
 */
export function isValidTimezone(timezone: string): boolean {
  return CANONICAL_TIMEZONES.some((tz) => tz.value === timezone);
}

/**
 * Get display name for a timezone
 */
export function getTimezoneLabel(timezone: string): string {
  const tz = CANONICAL_TIMEZONES.find((t) => t.value === timezone);
  return tz ? tz.label : timezone;
}
